### ISSUE TITLE
Confusion about the test setup

### ISSUE THREAD

**Issue by olivierobert** [VyTranSc/n_vy_asm#9]
1. There are both `spec` (for RSpec) and `test` (Minitest) directories in the project. Since only RSpec tests have been added, the `test` directory can be removed.

2. The README file stipulates that the following gems would be used:

![image](https://user-images.githubusercontent.com/696529/90108331-56c64280-dd74-11ea-86e7-41498f098fe7.png)

But the actual tests use `fabricator`:

https://github.com/VyTranSc/n_vy_asm/blob/ecae0a09024a64c880fa14cd8f8a8a506e74fd33/spec/models/uploaded_file_log_spec.rb#L4

https://github.com/VyTranSc/n_vy_asm/blob/ecae0a09024a64c880fa14cd8f8a8a506e74fd33/spec/services/keywords_services/create_spec.rb#L4

**Comment by VyTranSc** [comment]
1. Yes, you're right. The `test` folder can be cleaned up, I missed it when cleaning up the code. 

2. Sorry for the confusion, I think I made it a bit complicated to understand in README file :D. What I meant was those gems (`factory_bot_rails`, `faker` and `dotenv-rails`) are what I would usually used in a project. 

`fabricator`, `ffaker` and `figaro` are what I decided to use in this codebase because I've saw those from Nimble boilerplate and done some research, found that those are better and wanted to use those as a learning experience.
